name: volleyball_scout
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:

  flutter:
  
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^9.0.1
  riverpod_annotation: ^2.1.1
  dynamic_color: ^1.6.6
  firebase_core: ^2.14.0
  google_fonts: ^5.1.0

dev_dependencies:
  build_runner:
  custom_lint: ^0.4.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true
