name: volleyball_scout
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:

  flutter:
  
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^9.0.1
  riverpod_annotation: ^2.1.1
  dynamic_color: ^1.6.6
  firebase_core: ^2.14.0
  google_fonts: ^5.1.0
  flutter_native_splash: ^2.3.1

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/logo.png
  image_dark: assets/images/logo.png

dev_dependencies:
  build_runner:
  custom_lint: ^0.4.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets: 
    - assets/images/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"

